-- P3-3: Student Roadmaps
-- Two tables:
--   student_roadmaps   — one roadmap per student per course
--   roadmap_milestones — ordered steps inside a roadmap
--
-- Roadmaps are generated by AI (POST /api/roadmaps/:courseId/generate)
-- and can be re-generated at any time (replaces milestones in-place).
-- Students can manually mark milestones complete.

-- ── Roadmaps ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS student_roadmaps (
  id           BIGSERIAL    PRIMARY KEY,
  student_id   INT          NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  course_id    INT          NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title        TEXT         NOT NULL DEFAULT 'My Learning Roadmap',
  summary      TEXT,                         -- 2-3 sentence AI-generated overview
  generated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  UNIQUE (student_id, course_id)             -- one active roadmap per student per course
);

CREATE INDEX IF NOT EXISTS idx_roadmaps_student  ON student_roadmaps (student_id);
CREATE INDEX IF NOT EXISTS idx_roadmaps_course   ON student_roadmaps (course_id);

-- ── Milestones ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roadmap_milestones (
  id            BIGSERIAL    PRIMARY KEY,
  roadmap_id    BIGINT       NOT NULL REFERENCES student_roadmaps(id) ON DELETE CASCADE,
  step_order    INT          NOT NULL,        -- 1-based display order
  title         TEXT         NOT NULL,
  description   TEXT,
  resource_hint TEXT,                         -- e.g. "See Module 2 notes on recursion"
  status        TEXT         NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending', 'in_progress', 'completed')),
  completed_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_milestones_roadmap
  ON roadmap_milestones (roadmap_id, step_order);
